export const UserRoute = '/user';
export const UserLocationRoute = UserRoute + '/location';
export const UserDelete = UserRoute + '/delete';
export const UserProfileRoute = UserRoute + '/profile'
export const UserBookingsRoute = UserRoute + '/booking';
export const UserTransactionsRoute = UserRoute + '/transactions';
export const UserCompanionFindRoute = UserRoute + '/companionfind';
export const UserSessionRoute = UserRoute + '/session';
export const UserChatRoomRoute = UserRoute + '/chatrooms';
export const UserNotificationRoute = UserRoute + '/notifications';
export const UserIssuesRoute = UserRoute + '/issues';
